services:
  - type: worker
    name: tg-broker-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python broker_bot.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: GEOCODE_UA
        sync: false
